# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(607, 804)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(140, 390, 195, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_label = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_label.setFont(font)
        self.pushButton_label.setObjectName("pushButton_label")
        self.horizontalLayout.addWidget(self.pushButton_label)
        self.pushButton_xk = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_xk.setFont(font)
        self.pushButton_xk.setObjectName("pushButton_xk")
        self.horizontalLayout.addWidget(self.pushButton_xk)
        self.plainTextEdit_abs = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit_abs.setGeometry(QtCore.QRect(100, 110, 321, 261))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.plainTextEdit_abs.setFont(font)
        self.plainTextEdit_abs.setObjectName("plainTextEdit_abs")
        self.plainTextEdit_title = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit_title.setGeometry(QtCore.QRect(100, 40, 321, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.plainTextEdit_title.setFont(font)
        self.plainTextEdit_title.setObjectName("plainTextEdit_title")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 60, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 220, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(50, 680, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(50, 550, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.textBrowser_xk = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_xk.setGeometry(QtCore.QRect(130, 660, 256, 101))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textBrowser_xk.setFont(font)
        self.textBrowser_xk.setObjectName("textBrowser_xk")
        self.textBrowser_label = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_label.setGeometry(QtCore.QRect(130, 520, 256, 101))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textBrowser_label.setFont(font)
        self.textBrowser_label.setObjectName("textBrowser_label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton_label.setText(_translate("Dialog", "标签"))
        self.pushButton_xk.setText(_translate("Dialog", "学科"))
        self.label.setText(_translate("Dialog", "Title"))
        self.label_2.setText(_translate("Dialog", "Abstract"))
        self.label_3.setText(_translate("Dialog", "xueke"))
        self.label_4.setText(_translate("Dialog", "Label"))
